
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

server:
  address: 0.0.0.0
static:
  basePath: ${user.dir}
  imagePath: /src/main/contents/images/
